version: '3'
services:
    #PHP Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: php8.2
        container_name: php_admittedz
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - admittedz-network

    #Nginx Service
    webserver:
        image: nginx:1.24.0
        container_name: webserver_admittedz
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - admittedz-network

    #MySQL Service
    db:
        image: mysql:8.0.33
        container_name: db_admittedz
        restart: always
        tty: true
        ports:
            - "33066:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - admittedz-network
    #PHPMYADMIN
    phpmyadmin:
        image: phpmyadmin:5
        container_name: phpmyadmin_admittedz
        restart: always
        depends_on:
            - db
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db_admittedz
            UPLOAD_LIMIT: 20M
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_USERNAME}
        networks:
            - admittedz-network
    #ElasticSearch Service
    elastic:
        image: elasticsearch:7.17.9
        container_name: elastic_admittedz
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - admittedz-network

#Docker Networks
networks:
    admittedz-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
    elasticsearch-data:
        driver: local
